---

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/dev"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/prod"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/node"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/docker/dev"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/docker/prod"
    schedule:
      interval: "weekly"
