FROM python:3.8 as ptportalWebProdBase

RUN apt-get update && apt-get install -y \
  p7zip-full \
  nano \
  zip \
  netcat-openbsd \
  gunicorn

ADD docker/prod/requirements.txt .
RUN pip install --upgrade pip && \
    pip install -r ./requirements.txt


FROM python:3.8

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY --from=ptportalWebProdBase /usr/local/lib/python3.8/site-packages/ /usr/local/lib/python3.8/site-packages/
COPY --from=ptportalWebProdBase /usr/local/bin/ /usr/local/bin/
COPY --from=ptportalWebProdBase /usr/bin/ /usr/bin/
COPY --from=ptportalWebProdBase /bin/ /bin/

RUN mkdir -p /code/pentestportal/media
WORKDIR /code
